name: select_body_parts
description: "An anatomic body part selecting UI package for Flutter."
version: 0.0.1
homepage: https://github.com/OmerBurakTaskin/select_body_parts_flutter
publish_to: https://pub.dev

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  flutter_svg: ^2.0.0
  path_drawing: ^1.0.1

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

  assets:
    - assets/front_body.svg
    - assets/back_body.svg



